<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BLLGOPALREDDY" failures="1" tests="9" name="com.advaita.TestCreate.TestStagesCreate" time="27.422" errors="0" timestamp="2024-05-31T14:16:22 IST" skipped="0">
  <testcase classname="com.advaita.TestCreate.TestStagesCreate" name="navigateFetchRecord" time="11.497"/>
  <system-out/>
  <testcase classname="com.advaita.TestCreate.TestStagesCreate" name="VerifyStagesTabIsDisplayed" time="0.081"/>
  <system-out/>
  <testcase classname="com.advaita.TestCreate.TestStagesCreate" name="verifyCreateStagesButton" time="1.487"/>
  <system-out/>
  <testcase classname="com.advaita.TestCreate.TestStagesCreate" name="verifyStageNameTextBox" time="0.164"/>
  <system-out/>
  <testcase classname="com.advaita.TestCreate.TestStagesCreate" name="verifyStageSelectProcessDropDown" time="1.299"/>
  <system-out/>
  <testcase classname="com.advaita.TestCreate.TestStagesCreate" name="verifyStageSelectSubProcessDropDown" time="1.238"/>
  <system-out/>
  <testcase classname="com.advaita.TestCreate.TestStagesCreate" name="verifyStageSelectSubSubProcessDropDown" time="1.217"/>
  <system-out/>
  <testcase classname="com.advaita.TestCreate.TestStagesCreate" name="verifyStageCalculationTypeDropDown" time="8.349"/>
  <system-out/>
  <testcase classname="com.advaita.TestCreate.TestStagesCreate" name="verifyAddSectionA" time="2.090">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.advaita.WorkFlowDesign.PageObject.Stages.verifyAddSectionA(Stages.java:319)
at com.advaita.TestCreate.TestStagesCreate.verifyAddSectionA(TestStagesCreate.java:174)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAddSectionA -->
  <system-out/>
</testsuite> <!-- com.advaita.TestCreate.TestStagesCreate -->
