<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-30T13:31:12 IST" name="Default suite" finished-at="2024-08-30T13:32:08 IST" duration-ms="55889">
    <groups>
    </groups>
    <test started-at="2024-08-30T13:31:12 IST" name="Default test" finished-at="2024-08-30T13:32:08 IST" duration-ms="55889">
      <class name="com.advaita.TestCreate.TestDataSetCreate">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.advaita.TestCreate.TestDataSetCreate@385e36d4]" started-at="2024-08-30T13:31:12 IST" name="setUp" finished-at="2024-08-30T13:31:21 IST" duration-ms="8748" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyCreateNewDataset()[pri:2, instance:com.advaita.TestCreate.TestDataSetCreate@385e36d4]" started-at="2024-08-30T13:31:21 IST" name="verifyCreateNewDataset" finished-at="2024-08-30T13:32:07 IST" duration-ms="46395" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[maxLengthField is not enabled. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: maxLengthField is not enabled. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.advaita.DataSetUp.PageObject.DataSet.verifyMaxLengthField(DataSet.java:744)
at com.advaita.DataSetUp.PageObject.DataSet.enterFieldNameAndValidations(DataSet.java:688)
at com.advaita.TestCreate.TestDataSetCreate.verifyCreateNewDataset(TestDataSetCreate.java:117)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateNewDataset -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.advaita.TestCreate.TestDataSetCreate@385e36d4]" started-at="2024-08-30T13:32:07 IST" name="getResult" finished-at="2024-08-30T13:32:08 IST" duration-ms="680" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyCreateNewDataset status=FAILURE method=TestDataSetCreate.verifyCreateNewDataset()[pri:2, instance:com.advaita.TestCreate.TestDataSetCreate@385e36d4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.advaita.TestCreate.TestDataSetCreate@385e36d4]" started-at="2024-08-30T13:32:08 IST" name="tearDown" finished-at="2024-08-30T13:32:08 IST" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.advaita.TestCreate.TestDataSetCreate -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
